Parameters:
  IAMAccessKeyID:
    Description: The Access Key of your IAM user
    Type: String
    NoEcho: True
    MinLength: '16'
    MaxLength: '120'
    ConstraintDescription: Please enter correct Access Key ID.
  IAMSecretAccessKeyID:
    Description: The Secret Key of your IAM user
    Type: String
    NoEcho: True
    MinLength: '1'
    ConstraintDescription: Please enter the Secret Access Key ID.
  DestinationRegion:
    Description: The target region to deploy QuickSight solution.
    Type: String
    Default: us-east-1
    AllowedValues: 
      - us-east-1
      - us-east-2
      - us-west-2
      - eu-central-1 
      - eu-west-1 
      - eu-west-2 
      - ap-southeast-1 
      - ap-northeast-1 
      - ap-southeast-2 
      - ap-northeast-2 
      - ap-south-1
  QuickSightQueryMode:
    Description: Choose the QuickSight query mode. If you do not know what SPICE is, please keep default.
    Type: String
    Default: DIRECT_QUERY
    AllowedValues: 
      - DIRECT_QUERY
      - SPICE
  AthenaDatabaseName:
    Description: Please input the database name in Athena, which will be used to connect CUR data on S3. If you integrate Athena with CUR by official CloudFormation template, this should looks like "athenacurcfn_xxx".
    Type: String
    MinLength: '1'
    ConstraintDescription: Please input the database name in Athena, which will be used to connect CUR data on S3.
  AthenaDatabaseTableName:
    Description: Please input the table name in above Athena Database, which will be used to connect CUR data on S3.
    Type: String
    MinLength: '1'
    ConstraintDescription: Please input the table name in provided Database, which will be used to connect CUR data on S3.
  AthenaQueryResultLocation:
    Description: Please input the "Query result location" value from Settings in Athena console. If target region is us-east-1, this may looks like "s3://aws-athena-query-results-{YourAccountId}-us-east-1/"
    Type: String
    AllowedPattern: '^s3://.+/$'
    ConstraintDescription: Must start with "s3://" and end with "/".
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
  DeleteExistingResources:
    Description: Delete existing or failed Dashboard/Dataset/Datasource before create new ones.
    Type: String
    Default: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'
  DeleteResourcesOnly:
    Description: Just delete existing or failed Dashboard/Dataset/Datasource. Do not create new ones.
    Type: String
    Default: 'no'
    AllowedValues:
      - 'yes'
      - 'no'
  
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
  # AWSInstanceType2NATArch:
  #   t2.micro:
  #     Arch: NATHVM64
  #   t2.small:
  #     Arch: NATHVM64
  #   t2.medium:
  #     Arch: NATHVM64
  AWSRegionArch2AMI:
    af-south-1:
      HVM64: ami-064cc455f8a1ef504
      HVMG2: NOT_SUPPORTED
    ap-east-1:
      HVM64: ami-f85b1989
      HVMG2: NOT_SUPPORTED
    ap-northeast-1:
      HVM64: ami-0b2c2a754d5b4da22
      HVMG2: ami-09d0e0e099ecabba2
    ap-northeast-2:
      HVM64: ami-0493ab99920f410fc
      HVMG2: NOT_SUPPORTED
    ap-northeast-3:
      HVM64: ami-01344f6f63a4decc1
      HVMG2: NOT_SUPPORTED
    ap-south-1:
      HVM64: ami-03cfb5e1fb4fac428
      HVMG2: ami-0244c1d42815af84a
    ap-southeast-1:
      HVM64: ami-0ba35dc9caf73d1c7
      HVMG2: ami-0e46ce0d6a87dc979
    ap-southeast-2:
      HVM64: ami-0ae99b503e8694028
      HVMG2: ami-0c0ab057a101d8ff2
    ca-central-1:
      HVM64: ami-0803e21a2ec22f953
      HVMG2: NOT_SUPPORTED
    cn-north-1:
      HVM64: ami-07a3f215cc90c889c
      HVMG2: NOT_SUPPORTED
    cn-northwest-1:
      HVM64: ami-0a3b3b10f714a0ff4
      HVMG2: NOT_SUPPORTED
    eu-central-1:
      HVM64: ami-0474863011a7d1541
      HVMG2: ami-0aa1822e3eb913a11
    eu-north-1:
      HVM64: ami-0de4b8910494dba0f
      HVMG2: ami-32d55b4c
    eu-south-1:
      HVM64: ami-08427144fe9ebdef6
      HVMG2: NOT_SUPPORTED
    eu-west-1:
      HVM64: ami-015232c01a82b847b
      HVMG2: ami-0d5299b1c6112c3c7
    eu-west-2:
      HVM64: ami-0765d48d7e15beb93
      HVMG2: NOT_SUPPORTED
    eu-west-3:
      HVM64: ami-0caf07637eda19d9c
      HVMG2: NOT_SUPPORTED
    me-south-1:
      HVM64: ami-0744743d80915b497
      HVMG2: NOT_SUPPORTED
    sa-east-1:
      HVM64: ami-0a52e8a6018e92bb0
      HVMG2: NOT_SUPPORTED
    us-east-1:
      HVM64: ami-032930428bf1abbff
      HVMG2: ami-0aeb704d503081ea6
    us-east-2:
      HVM64: ami-027cab9a7bf0155df
      HVMG2: NOT_SUPPORTED
    us-west-1:
      HVM64: ami-088c153f74339f34c
      HVMG2: ami-0a7fc72dc0e51aa77
    us-west-2:
      HVM64: ami-01fee56b22f308154
      HVMG2: ami-0fe84a5b4563d8f27

Resources:
  QSCURBuilder:
    Type: "AWS::EC2::Instance"
    Description: "This EC2 will run a bash script to build QuickSight solution."
    Properties:      
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType:
        Ref: InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref BuilderSecurityGroup
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |+
              #!/bin/bash
              yum install -y jq
            - 'export ACCESSKEY='
            - !Ref IAMAccessKeyID
            - |+

            - 'echo ACCESSKEY='
            - !Ref IAMAccessKeyID
            - '>> /etc/profile'
            - |+
              
            - 'export SECRETKEY='
            - !Ref IAMSecretAccessKeyID
            - |+

            - 'echo SECRETKEY='
            - !Ref IAMSecretAccessKeyID
            - '>> /etc/profile'
            - |+

            - 'export REGIONCUR='
            - !Ref DestinationRegion
            - |+

            - 'echo REGIONCUR='
            - !Ref DestinationRegion
            - '>> /etc/profile'
            - |+

            - 'export QUERYMODE='
            - !Ref QuickSightQueryMode
            - |+

            - 'echo QUERYMODE='
            - !Ref QuickSightQueryMode
            - '>> /etc/profile'
            - |+

            - 'export ATHENADB='
            - !Ref AthenaDatabaseName
            - |+

            - 'echo ATHENADB='
            - !Ref AthenaDatabaseName
            - '>> /etc/profile'
            - |+

            - 'export ATHENATABLE='
            - !Ref AthenaDatabaseTableName
            - |+

            - 'echo ATHENATABLE='
            - !Ref AthenaDatabaseTableName
            - '>> /etc/profile'
            - |+

            - 'export OUTPUTBUCKET='
            - !Ref AthenaQueryResultLocation
            - |+

            - 'echo OUTPUTBUCKET='
            - !Ref AthenaQueryResultLocation
            - '>> /etc/profile'
            - |+

            - 'export DELETEEXISTINGRESOURCE='
            - !Ref DeleteExistingResources
            - |+

            - 'echo DELETEEXISTINGRESOURCE='
            - !Ref DeleteExistingResources
            - '>> /etc/profile'
            - |+

            - 'export DELETEONLY='
            - !Ref DeleteResourcesOnly
            - |+

            - 'echo DELETEONLY='
            - !Ref DeleteResourcesOnly
            - '>> /etc/profile'
            - |+

              curl -L -O https://github.com/adamhucn/quicksight-cur-deployment-cfn/archive/master.zip
              unzip master.zip -d /home/ec2-user/ >> /home/ec2-user/qscurlog.txt
              cd /home/ec2-user/quicksight-cur-deployment-cfn-master
              echo "" >> /home/ec2-user/qscurlog.txt
              bash deployQSCUR_cfn.sh >> /home/ec2-user/qscurlog.txt

  BuilderSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation

Outputs:
  SSHCOMMAND:
    Value: !Join 
      - ''
      - - 'ssh -i '
        - !Ref KeyName
        - '.pem ec2-user@'
        - !GetAtt 
          - QSCURBuilder
          - PublicIp
    Description: SSH to QSCURBuilder EC2 instance.
